#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Masahiro Yasui
# SPDX-License-Identifier: BSD-3-Clause

import sys
import re

def removeAlphabet(string, remove_chars):
    return re.sub(f"[{re.escape(remove_chars)}]", " ", string) if remove_chars else string

if __name__ == "__main__":
    remove_chars = sys.argv[1] if len(sys.argv) > 1 else ""
    text = sys.stdin.read().strip()
    print(removeAlphabet(text, remove_chars))

